### ISSUE TITLE
closeBtn 这个配置不能用呀！

### ISSUE THREAD

**Issue by JohyC** [Liweifei/layer-for-vue#1]
closeBtn 1，2，0都设置了，没反应呀。其他参数都没问题。
closeBtn 为0 页面class 还是  layui-layer-close2 ；没变化。
![image](https://user-images.githubusercontent.com/38210128/153105477-16a689e4-21b5-44ca-b82b-a4e2fa22e7bf.png)

**Comment by Liweifei** [comment]
你好，0 暂时未作兼容处理，主要用作普通弹窗作用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Liweifei/layer-for-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 上午9:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Liweifei/layer-for-vue] closeBtn 这个配置不能用呀！ (Issue #1)





 
closeBtn 1，2，0都设置了，没反应呀。其他参数都没问题。
  <layer-iframe v-model="showMonitor" :title="false" skin="layer-custom" :area="customArea" :shade="[0.7,'#000']" closeBtn="0" offset="auto" :anim="5" :minStack="false" @end="closeLayer" &gt; <div class="monitor-swiper"  @click="isPlay"&gt; <div class="swiper-wrapper"&gt; <div class="swiper-slide" v-for="(item, index) in monitorUrl" :key="index" &gt; <div class="relative"&gt; <div :id="monitor${index}`"&gt;
 
 
 
       <div class="swiper-button-prev swiper-button-white"&gt;</div&gt;       <div class="swiper-button-next swiper-button-white"&gt;</div&gt;     </div&gt;     <!-- <div class="monitor-wapper" @click="isPlay" v-if="showMonitor"&gt;       <div class="monitor-content"&gt;       </div&gt;     </div&gt; --&gt;   </layer-iframe&gt;`  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
